# List of all properties at https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

logging:
  level:
    com.mladen.cikara.oauth2: trace
    org.springframework: info

spring:
  flyway:
    enabled: false
  jpa:
    generate-ddl: true
    properties:
      hibernate.ddl-auto: create # Use this to see what would Hibernate create in database.