# List of all properties at https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

logging:
  level:
    com.mladen.cikara.oauth2: trace

spring:
  datasource:
    url: jdbc:postgresql://localhost:1111/oauth2-test
    username: oauth2user
    password: oauth2user
