CREATE USER oauth2user WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

ALTER ROLE oauth2user WITH PASSWORD 'oauth2user';

REVOKE ALL ON SCHEMA public FROM oauth2user;